### ISSUE TITLE
return types of RtTypeInfo._init_GUID is inconsistent 

### ISSUE THREAD

**Issue by thqby** [Lexikos/winrt.ahk#2] opened 2022-07-09 05:34 UTC
Inconsistent return types of rttypeinfo._init_GUID may raise errors or unexpected results in  `_rt_MetaDataLocate` and `iunknown_queryInterface` functions.

**Comment by Lexikos** [comment] 2022-07-23 01:37
`rttypeinfo.GUID` is intended to return a `GUID` for instantiated generic types (i.e. types with a calculated PIID) and a pointer for all other types. This is because many types are not parameterized, and already have the GUID in persistent memory, but parameterized types need a GUID calculated and stored somewhere.

Can you provide a minimal reproducible example of errors or unexpected results in `_rt_MetaDataLocate`? I think merely changing `pguid +` to `pguid,` would allow it to work with a GUID object, but that shouldn't be necessary in the first place because `_rt_MetaDataLocate` receives only base types like ``IVector`1``, not parameterized like ``IVector`1<String>``.

d288fb5 changes String to GuidToString for iunknown_queryInterface (actually CreateComMethodTable), which is necessary for non-parameterized delegate types (such as AsyncActionCompletedHandler for IAsyncAction.Completed) to work.

**Comment by thqby** [comment] 2022-07-23 02:29
[d288fb5](https://github.com/Lexikos/winrt.ahk/commit/d288fb571866bd8f115d6b342ba4e0953ce1756f) I found a mistake here in earlier versions.

`_rt_MetaDataLocate` Whether the guid object will appear here has not been verified.

**Comment by Lexikos** [comment] 2022-07-23 07:04
I'm not sure that I get your meaning.

I think you are saying that you found the issue (and reported it) prior to d288fb5, but I already know that, because I committed d288fb5 in response to your report.

I guess you mean that the "errors or unexpected results in `_rt_MetaDataLocate`" was just conjecture on your part, and there is no actual issue remaining.

**Comment by thqby** [comment] 2022-07-23 07:42
I mean `xx.GUID` may return a `GUID` object or GUID pointer. And in the function `_ rt_metadatalocate`, must the expression `pguid : = t.GUID` be a guid pointer? If not, the following expression `pguid+8` will have problems.

**Comment by Lexikos** [comment] 2022-07-28 08:06
I think we're going backwards.

>  I think merely changing `pguid +` to `pguid,` would allow it to work with a GUID object, but that shouldn't be necessary in the first place because `_rt_MetaDataLocate` receives only base types like ``IVector`1``, not parameterized like ``IVector`1<String>``.

`pguid` is only an object if the type is parameterized, like ``A`1<B>``, not ``A`1``. With a nested parameterized type like ``A`1<B`1<C>>``, `_rt_MetaDataLocate` will receive ``A`1``, ``B`1``, `C` (if it isn't a fundamental type).

**Closed as completed** 2022-07-30 09:16 UTC
